version: "3"

services:
  mininet:
    image: opennetworking/p4mn
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ./mininet:/mininet
    entrypoint: "mn --custom bmv2.py --switch simple_switch_grpc --controller none"

  p4runtime:
    image: p4lang/p4runtime-sh
    hostname: p4runtime
    container_name: p4runtime
    privileged: true
    #tty: true
    #stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ./p4build:/p4build
      - ./p4runtime:/p4runtime
    links: 
      - mininet
    entrypoint: "/p4runtime/docker_entry_point.sh"
    #entrypoint: "/bin/bash"
    depends_on:
      - mininet
